#spring:
#  h2:
#    console:
#      enabled: true

server:
  port: 9192

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/JWTAUTHDB?createDatabaseIfNotExist=true
#    username: root
#    password: Softgen@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace